version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      - echo "Installing Composer..."
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
      - composer --version

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
      - echo "Caching Laravel configs..."
      - php artisan config:cache
      - php artisan view:cache

  build:
    commands:
      - echo "Zipping application for deployment..."
      - zip -r application.zip . -x "vendor/*" ".git/*" ".gitignore" ".env*" "tests/*" "node_modules/*" "*.md"

artifacts:
  files:
    - application.zip
