version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      - echo "Installing Composer..."
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
      - composer --version

  pre_build:
    commands:
      - echo "Navigating to Laravel root directory..."
      - cd /codebuild/output/src* || cd /var/www/html
      - pwd  # Debugging step to confirm the correct directory
      - echo "Installing dependencies..."
      - composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

      - echo "Generating Laravel environment file..."
      - |
        cat > .env <<EOF
        APP_NAME=Laravel
        APP_ENV=${APP_ENV}
        APP_KEY=
        APP_DEBUG=${APP_DEBUG}
        APP_URL=${APP_URL}

        DB_CONNECTION=mysql
        DB_HOST=${DB_HOST}
        DB_PORT=${DB_PORT}
        DB_DATABASE=${DB_DATABASE}
        DB_USERNAME=${DB_USERNAME}
        DB_PASSWORD=${DB_PASSWORD}

        CACHE_DRIVER=file
        QUEUE_CONNECTION=sync
        SESSION_DRIVER=file
        SESSION_LIFETIME=120
        EOF

      - echo "Setting permissions for .env..."
      - chmod 644 .env
      - ls -la .env  # Debugging step to confirm .env exists

      - echo "Generating application key..."
      - php artisan key:generate || echo "Key generate failed but continuing..."
      
      - echo "Caching Laravel configs..."
      - php artisan config:cache || echo "Config cache failed but continuing..."
      - php artisan view:cache || echo "View cache failed but continuing..."

  build:
    commands:
      - echo "Running Laravel migrations..."
      - php artisan migrate --force || echo "Migration failed but continuing..."
      - echo "Zipping application for deployment..."
      - zip -r application.zip . -x "vendor/*" ".git/*" ".gitignore" ".env*" "tests/*" "node_modules/*" "*.md"

artifacts:
  files:
    - application.zip
