version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      - echo "Installing Composer..."
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
      - composer --version

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
      - echo "Generating Laravel environment file..."
      - |
        cat > .env <<EOF
        APP_NAME=Laravel
        APP_ENV=${APP_ENV}
        APP_KEY=
        APP_DEBUG=${APP_DEBUG}
        APP_URL=https://your-app-domain.com

        DB_CONNECTION=mysql
        DB_HOST=${DB_HOST}
        DB_PORT=${DB_PORT}
        DB_DATABASE=${DB_DATABASE}
        DB_USERNAME=${DB_USERNAME}
        DB_PASSWORD=${DB_PASSWORD}

        CACHE_DRIVER=file
        QUEUE_CONNECTION=sync
        SESSION_DRIVER=file
        SESSION_LIFETIME=120
        EOF
      - php artisan key:generate
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache

  build:
    commands:
      - echo "Zipping application for deployment..."
      - zip -r application.zip . -x "vendor/*" ".git/*" ".gitignore" ".env.example" "tests/*" "node_modules/*" "*.md"

artifacts:
  files:
    - application.zip
